# Generated by Django 5.1.6 on 2025-03-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='code',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
