# Generated by Django 5.1.6 on 2025-02-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_alter_uservote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservote',
            name='user',
        ),
    ]
