# Generated by Django 5.1.6 on 2025-02-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('userpanel', '0003_remove_uservote_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='uservote',
            constraint=models.UniqueConstraint(fields=('election', 'selected_option'), name='unique_vote_per_election'),
        ),
    ]
