# Generated by Django 5.1.6 on 2025-02-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0004_uservote_unique_vote_per_election'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uservote',
            name='unique_vote_per_election',
        ),
    ]
