# Generated by Django 5.1.6 on 2025-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('total_active_users', models.IntegerField(default=0)),
            ],
        ),
    ]
