# Generated by Django 5.1.6 on 2025-02-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='declared_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_winner', to='adminpanel.option'),
        ),
        migrations.AddField(
            model_name='election',
            name='winner_declared',
            field=models.BooleanField(default=False),
        ),
    ]
