# Generated by Django 5.1.6 on 2025-02-16 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('userpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='VoteTitle',
        ),
        migrations.RenameField(
            model_name='voteoption',
            old_name='vote',
            new_name='vote_title',
        ),
    ]
