# Generated by Django 5.1.6 on 2025-02-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='created_by',
        ),
    ]
